-- ===========================================================
-- FB VEÍCULOS — script de configuração do banco de dados
--
-- COMO USAR (uma vez só):
-- 1. Crie um projeto grátis em https://supabase.com
-- 2. No menu lateral, abra "SQL Editor"
-- 3. Clique em "New query", cole TODO este arquivo, e clique em "Run"
-- 4. Pronto — a tabela é criada já com os 24 veículos de exemplo.
--
-- Depois disso você NUNCA MAIS precisa mexer em SQL. Todo o dia a dia
-- (adicionar, editar, remover veículo) é feito pela tela em admin.html.
--
-- Depois de rodar este script, copie a "Project URL" e a chave
-- "anon public" (Project Settings → API) e cole em main.js.
-- ===========================================================

create table if not exists veiculos (
  id          bigint generated by default as identity primary key,
  categoria   text not null,
  nome        text not null,
  slug        text not null unique,
  foto        text,
  preco       numeric(10,2) not null default 0,
  ano         text not null default '',
  km          integer not null default 0,
  cambio      text not null default '',
  combustivel text not null default '',
  cor         text not null default '',
  opcionais   text not null default '',
  destaque    boolean not null default false,
  descricao   text not null default '',
  ativo       boolean not null default true,
  criado_em   timestamptz not null default now()
);

-- liga a segurança da tabela
alter table veiculos enable row level security;

-- qualquer pessoa (o site) pode LER os veículos
drop policy if exists "Leitura publica" on veiculos;
create policy "Leitura publica" on veiculos
  for select using (true);

-- só quem estiver logado (a lojista, pelo admin.html) pode
-- adicionar, editar ou remover veículos
drop policy if exists "Escrita autenticada" on veiculos;
create policy "Escrita autenticada" on veiculos
  for all to authenticated using (true) with check (true);

-- apaga veículos de execuções anteriores deste script, pra poder rodar de novo sem duplicar
delete from veiculos;

-- os 24 veículos de exemplo (ponto de partida — edite ou apague pelo admin.html)
insert into veiculos (categoria, nome, slug, foto, preco, ano, km, cambio, combustivel, cor, opcionais, destaque, descricao, ativo) values
  ('Hatches', 'Chevrolet Onix LT 1.0', 'chevrolet-onix-lt', NULL, 74900, '2021/2022', 38000, 'Manual', 'Flex', 'Prata', 'Ar-condicionado;Direção elétrica;Multimídia', true, 'Único dono, revisado, manual e chave reserva.', true),
  ('Hatches', 'Volkswagen Gol 1.6 MSI', 'volkswagen-gol-msi', NULL, 58900, '2019/2020', 61000, 'Manual', 'Flex', 'Branco', 'Ar-condicionado;Vidro elétrico', false, 'Econômico, ideal para o dia a dia na cidade.', true),
  ('Hatches', 'Fiat Argo Drive 1.3', 'fiat-argo-drive', NULL, 69900, '2020/2021', 45000, 'Manual', 'Flex', 'Vermelho', 'Multimídia;Câmera de ré;Sensor de estacionamento', true, 'Design moderno, ótimo custo-benefício.', true),
  ('Hatches', 'Hyundai HB20 Comfort 1.0', 'hyundai-hb20-comfort', NULL, 71900, '2021/2021', 42000, 'Manual', 'Flex', 'Cinza', 'Ar-condicionado;Direção elétrica;Central multimídia', false, 'Revisões em dia, pneus novos, pronto pra rodar.', true),
  ('Sedãs', 'Toyota Corolla XEi 2.0', 'toyota-corolla-xei', NULL, 139900, '2020/2021', 52000, 'Automático', 'Flex', 'Prata', 'Bancos em couro;Teto solar;Câmera 360°', true, 'Top de linha, impecável, todas as revisões na concessionária.', true),
  ('Sedãs', 'Honda Civic EXL 2.0', 'honda-civic-exl', NULL, 118900, '2018/2019', 68000, 'Automático', 'Flex', 'Preto', 'Bancos em couro;Piloto automático;Multimídia', false, 'Conforto e economia em um dos sedãs mais procurados do mercado.', true),
  ('Sedãs', 'Chevrolet Cruze LT 1.4 Turbo', 'chevrolet-cruze-lt', NULL, 94900, '2019/2020', 57000, 'Automático', 'Flex', 'Branco', 'Central multimídia;Ar digital', false, 'Motor turbo, ótimo desempenho e economia.', true),
  ('Sedãs', 'Nissan Versa Sense 1.6', 'nissan-versa-sense', NULL, 76900, '2021/2022', 33000, 'Manual', 'Flex', 'Prata', 'Ar-condicionado;Vidro elétrico;Trava elétrica', true, 'Baixa quilometragem, único dono, todo revisado.', true),
  ('SUVs', 'Jeep Compass Longitude 1.3 T', 'jeep-compass-longitude', NULL, 154900, '2021/2022', 41000, 'Automático', 'Flex', 'Cinza', 'Teto solar;Bancos em couro;Central 8.4"', true, 'SUV completo, revisado na concessionária, garantia de fábrica.', true),
  ('SUVs', 'Hyundai Creta Prestige 2.0', 'hyundai-creta-prestige', NULL, 129900, '2020/2021', 47000, 'Automático', 'Flex', 'Branco', 'Câmera de ré;Central multimídia;Sensor de estacionamento', true, 'Completo, pneus novos, impecável por dentro e por fora.', true),
  ('SUVs', 'Volkswagen T-Cross 200 TSI', 'volkswagen-tcross-tsi', NULL, 119900, '2020/2020', 53000, 'Automático', 'Flex', 'Vermelho', 'Multimídia;Ar digital;Piloto automático', false, 'Motor turbo 1.0, ágil e econômico.', true),
  ('SUVs', 'Chevrolet Tracker LT 1.0 Turbo', 'chevrolet-tracker-lt', NULL, 112900, '2022/2022', 24000, 'Automático', 'Flex', 'Preto', 'Central multimídia;Câmera de ré', false, 'Baixíssima km, praticamente novo, único dono.', true),
  ('Picapes', 'Fiat Toro Freedom 1.8', 'fiat-toro-freedom', NULL, 129900, '2020/2021', 56000, 'Automático', 'Flex', 'Branco', 'Central multimídia;Câmera de ré;Rack de teto', true, 'Robusta e versátil, ideal pra trabalho e lazer.', true),
  ('Picapes', 'Chevrolet S10 LTZ 2.8 Diesel', 'chevrolet-s10-ltz', NULL, 189900, '2019/2020', 72000, 'Automático', 'Diesel', 'Prata', '4x4;Bancos em couro;Teto solar', true, 'Tração 4x4, motor diesel, revisões em dia.', true),
  ('Picapes', 'Volkswagen Saveiro Trendline 1.6', 'volkswagen-saveiro-trendline', NULL, 82900, '2021/2021', 39000, 'Manual', 'Flex', 'Prata', 'Ar-condicionado;Direção elétrica', false, 'Cabine simples, ótima pra transporte de carga leve.', true),
  ('Picapes', 'Toyota Hilux SRV 2.8 Diesel', 'toyota-hilux-srv', NULL, 249900, '2019/2019', 81000, 'Automático', 'Diesel', 'Preto', '4x4;Bancos em couro;Central multimídia', false, 'A picape mais desejada do Brasil, toda revisada.', true),
  ('Utilitários', 'Fiat Fiorino Furgão 1.4', 'fiat-fiorino-furgao', NULL, 69900, '2020/2021', 64000, 'Manual', 'Flex', 'Branco', 'Ar-condicionado;Direção hidráulica', false, 'Ideal para pequenos comércios e entregas.', true),
  ('Utilitários', 'Renault Kangoo Express 1.6', 'renault-kangoo-express', NULL, 64900, '2018/2019', 75000, 'Manual', 'Flex', 'Branco', 'Porta lateral dupla;Ar-condicionado', false, 'Amplo espaço de carga, bem conservada.', true),
  ('Utilitários', 'Peugeot Partner Furgão 1.6', 'peugeot-partner-furgao', NULL, 71900, '2019/2020', 58000, 'Manual', 'Flex', 'Prata', 'Ar-condicionado;Vidro elétrico', false, 'Ótimo custo-benefício para uso comercial.', true),
  ('Utilitários', 'Fiat Doblô Cargo 1.4', 'fiat-doblo-cargo', NULL, 66900, '2018/2018', 80000, 'Manual', 'Flex', 'Branco', 'Direção hidráulica', false, 'Espaçosa e resistente, pronta para o trabalho.', true),
  ('Motos', 'Honda CG 160 Titan', 'honda-cg-160-titan', NULL, 15900, '2021/2022', 18000, 'Manual', 'Flex', 'Vermelho', 'Partida elétrica;Freio CBS', true, 'A moto mais vendida do Brasil, revisada e pronta pra uso.', true),
  ('Motos', 'Yamaha Factor 125', 'yamaha-factor-125', NULL, 11900, '2020/2020', 22000, 'Manual', 'Flex', 'Azul', 'Partida elétrica', false, 'Econômica e leve, ótima para o dia a dia.', true),
  ('Motos', 'Honda Biz 125', 'honda-biz-125', NULL, 12900, '2021/2021', 19000, 'Automático', 'Flex', 'Prata', 'Partida elétrica;Freio CBS', true, 'Baixo consumo, ideal para cidade, único dono.', true),
  ('Motos', 'Yamaha Fazer 250', 'yamaha-fazer-250', NULL, 19900, '2019/2020', 31000, 'Manual', 'Flex', 'Preto', 'Freio ABS;Painel digital', false, 'Potente e confortável, ótima para viagens.', true);
